package xsd.mnpprotocol;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2025-03-03T16:17:13.574+05:30
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "MNPProtocol.xsd", name = "mnpservicePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MnpservicePort {

    @WebMethod(action = "send")
    public void send(

        @WebParam(partName = "param", name = "MNPFrame", targetNamespace = "MNPProtocol.xsd")
        MNPFrame param
    );
}
