
package com.example.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "checkCAPRegenRequestService", targetNamespace = "http://oap/services/checkCAPRegenRequestService", wsdlLocation = "file:/D:/backup/office/CapRegenRequest.wsdl")
public class CheckCAPRegenRequestService
    extends Service
{

    private final static URL CHECKCAPREGENREQUESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKCAPREGENREQUESTSERVICE_EXCEPTION;
    private final static QName CHECKCAPREGENREQUESTSERVICE_QNAME = new QName("http://oap/services/checkCAPRegenRequestService", "checkCAPRegenRequestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/backup/office/CapRegenRequest.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKCAPREGENREQUESTSERVICE_WSDL_LOCATION = url;
        CHECKCAPREGENREQUESTSERVICE_EXCEPTION = e;
    }

    public CheckCAPRegenRequestService() {
        super(__getWsdlLocation(), CHECKCAPREGENREQUESTSERVICE_QNAME);
    }

    public CheckCAPRegenRequestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKCAPREGENREQUESTSERVICE_QNAME, features);
    }

    public CheckCAPRegenRequestService(URL wsdlLocation) {
        super(wsdlLocation, CHECKCAPREGENREQUESTSERVICE_QNAME);
    }

    public CheckCAPRegenRequestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKCAPREGENREQUESTSERVICE_QNAME, features);
    }

    public CheckCAPRegenRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckCAPRegenRequestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckCAPRegenRequestPortType
     */
    @WebEndpoint(name = "checkCAPRegenRequest")
    public CheckCAPRegenRequestPortType getCheckCAPRegenRequest() {
        return super.getPort(new QName("http://oap/services/checkCAPRegenRequestService", "checkCAPRegenRequest"), CheckCAPRegenRequestPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckCAPRegenRequestPortType
     */
    @WebEndpoint(name = "checkCAPRegenRequest")
    public CheckCAPRegenRequestPortType getCheckCAPRegenRequest(WebServiceFeature... features) {
        return super.getPort(new QName("http://oap/services/checkCAPRegenRequestService", "checkCAPRegenRequest"), CheckCAPRegenRequestPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKCAPREGENREQUESTSERVICE_EXCEPTION!= null) {
            throw CHECKCAPREGENREQUESTSERVICE_EXCEPTION;
        }
        return CHECKCAPREGENREQUESTSERVICE_WSDL_LOCATION;
    }

}
