package xsd.mnpprotocol;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-17T13:10:00.501+05:30
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "mnpservice",
                  wsdlLocation = "file:/C:/Users/ADMIN/AppData/Local/Temp/tempdir375585544146309574.tmp/mnpservice_1.wsdl",
                  targetNamespace = "MNPProtocol.xsd")
public class Mnpservice extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("MNPProtocol.xsd", "mnpservice");
    public static final QName MnpservicePort = new QName("MNPProtocol.xsd", "mnpservicePort");
    static {
        URL url = null;
        try {
            url = URI.create("file:/C:/Users/ADMIN/AppData/Local/Temp/tempdir375585544146309574.tmp/mnpservice_1.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Mnpservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ADMIN/AppData/Local/Temp/tempdir375585544146309574.tmp/mnpservice_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Mnpservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Mnpservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Mnpservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Mnpservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Mnpservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Mnpservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MnpservicePort
     */
    @WebEndpoint(name = "mnpservicePort")
    public MnpservicePort getMnpservicePort() {
        return super.getPort(MnpservicePort, MnpservicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MnpservicePort
     */
    @WebEndpoint(name = "mnpservicePort")
    public MnpservicePort getMnpservicePort(WebServiceFeature... features) {
        return super.getPort(MnpservicePort, MnpservicePort.class, features);
    }

}
