
package xsd.mnpprotocol;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-17T13:10:00.464+05:30
 * Generated source version: 4.0.5
 *
 */
public final class MnpservicePort_MnpservicePort_Client {

    private static final QName SERVICE_NAME = new QName("MNPProtocol.xsd", "mnpservice");

    private MnpservicePort_MnpservicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Mnpservice.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        Mnpservice ss = new Mnpservice(wsdlURL, SERVICE_NAME);
        MnpservicePort port = ss.getMnpservicePort();

        {
        System.out.println("Invoking send...");
        xsd.mnpprotocol.MNPFrame _send_param = null;
//        port.send(_send_param);


        }

        System.exit(0);
    }

}
